FROM arm64v8/node:18-alpine

# Set the working directory
WORKDIR /usr/src/app

# Install python (for @discord/opus) and build tools
RUN apk add --no-cache python3 make g++

# Install app dependencies
COPY package*.json ./
RUN npm ci --omit=dev

# Bundle app source
COPY . .
CMD [ "npm", "start" ]